[package]
name = "client"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.69"
blockchain = { path = "../blockchain" }
clap = "3.0.0-beta.2"
common = { path = "../common" }
serde_json = "1.0"
tracing = "0.1.37"
